### ISSUE TITLE
Support more labels with different statuses

### ISSUE THREAD

**Issue by johlju** [ahmed-taj/probot-review-me#1]
When evaluating this app it seemed it can only handle one label when status is in one state. Would be great if this could handle more labels when status are in different states (for example first match will be used).

**Comment by z0al** [comment]
Hey @johlju, Thanks for giving this app a try 👍 

Would you like to elaborate more on this?

**Comment by johlju** [comment]
I thought of something like this. Apologize if this is not correct YAML, but hopefully you get an idea of what I mean. 

First hit in the order written in yml will be true.

```yml
# List of contexts (i.e. apps) and their corresponding statuses
# Allowed statuses are:
#
#   - success
#   - failure
#   - pending
#   - error

- when:
    # Using 'detectMergeConflicts: no' should be equal to leave it out entirely.
    detectMergeConflicts: no
    statuses:
      cla-bot: failure

    label: waiting for CLA pass

    # Optional comment written when setting the label
    commentWhenSettingLabel: >
      Waiting for...
      When signed the..

    # Optional, removes all of these labels when setting 'label:'.
    removeLabels:
      - needs review
      - waiting for code fix

- when:
    detectMergeConflicts: yes
    statuses:
      continuous-integration/travis-ci/pr: failure
      cla-bot: success
      wip: success

    label: waiting for code fix

    commentWhenSettingLabel: >
      CI pipeline failed...

    removeLabels:
      - needs review
      - waiting for CLA pass


- when:
    detectMergeConflicts: yes
    statuses:
      continuous-integration/travis-ci/pr: success
      cla-bot: success
      wip: success

    label: needs review

    removeLabels:
      - waiting for code fix
      - waiting for CLA pass
```
